export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"博客主页","i":"home"},["/README.md"]],
  ["v-2e3eac9e","/slides.html",{"e":"<!-- markdownlint-disable MD024 MD051 -->\n","y":"s","t":"幻灯片页","i":"person-chalkboard"},[":md"]],
  ["v-4e65ec78","/demo/disable.html",{"c":["使用指南"],"g":["禁用"],"e":"<p>你可以通过设置页面的 Frontmatter，在页面禁用功能与布局。</p>\n","y":"a","t":"布局与功能禁用","i":"gears","O":3},[":md"]],
  ["v-c151bf32","/demo/encrypt.html",{"c":["使用指南"],"g":["文章加密"],"n":true,"y":"a","t":"密码加密的文章","i":"lock"},[":md"]],
  ["v-438ffe52","/demo/markdown.html",{"c":["使用指南"],"g":["Markdown"],"e":"<p>VuePress 主要从 Markdown 文件生成页面。因此，你可以使用它轻松生成文档或博客站点。</p>\n<p>你应该创建和编写 Markdown 文件，以便 VuePress 可以根据文件结构将它们转换为不同的页面。</p>\n","y":"a","t":"Markdown 展示","i":"fab fa-markdown","O":2},[":md"]],
  ["v-6e19edb7","/demo/page.html",{"a":"一日长安","d":1577836800000,"l":"2020年1月1日","c":["使用指南"],"g":["页面配置","使用指南"],"u":true,"e":"<p><code>more</code> 注释之前的内容被视为文章摘要。</p>\n","y":"a","t":"页面配置","i":"file","O":1},[":md"]],
  ["v-1473bf53","/demo/",{"c":["使用指南"],"e":"<h2> 目录</h2>\n<ul>\n<li>\n<p><a href=\"/demo/markdown.html\" target=\"blank\">Markdown 展示</a></p>\n</li>\n<li>\n<p><a href=\"/demo/page.html\" target=\"blank\">页面展示</a></p>\n</li>\n<li>\n<p><a href=\"/demo/disable.html\" target=\"blank\">禁用展示</a></p>\n</li>\n<li>\n<p><a href=\"/demo/encrypt.html\" target=\"blank\">加密展示</a></p>\n</li>\n</ul>","y":"a","t":"主要功能与配置演示","i":"laptop-code"},["/demo/README.md"]],
  ["v-fffb8e28","/guide/",{"e":"<h2> 功能亮点</h2>\n<h3> Bar</h3>\n<ul>\n<li><a href=\"/guide/bar/baz.html\" target=\"blank\">baz</a></li>\n<li>...</li>\n</ul>\n<h3> Foo</h3>\n<ul>\n<li><a href=\"/guide/foo/ray.html\" target=\"blank\">ray</a></li>\n<li>...</li>\n</ul>\n","y":"a","t":"指南","i":"lightbulb"},["/guide/README.md"]],
  ["v-177e1f06","/guide/bar/baz.html",{"e":"<p>功能详情...</p>\n","y":"a","t":"Baz","i":"circle-info"},[":md"]],
  ["v-5d5c2d30","/guide/bar/",{"e":"<h2> 介绍</h2>\n<p>我们支持 bar 功能，...</p>\n<h2> 详情</h2>\n<ul>\n<li><a href=\"/guide/bar/baz.html\" target=\"blank\">baz</a></li>\n<li>...</li>\n</ul>\n","y":"a","t":"Bar 功能","i":"lightbulb"},["/guide/bar/README.md"]],
  ["v-0b6fc5f8","/guide/foo/ray.html",{"e":"<p>功能详情...</p>\n","y":"a","t":"Ray","i":"circle-info"},[":md"]],
  ["v-5d5821d6","/guide/foo/",{"e":"<h2> 介绍</h2>\n<p>我们支持 foo 功能，...</p>\n<h2> 详情</h2>\n<ul>\n<li><a href=\"/guide/foo/ray.html\" target=\"blank\">ray</a></li>\n<li>...</li>\n</ul>\n","y":"a","t":"Foo 功能","i":"lightbulb"},["/guide/foo/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-5bc93818","/category/",{"y":"p","t":"分类","I":false},[]],
  ["v-744d024e","/tag/",{"y":"p","t":"标签","I":false},[]],
  ["v-e52c881c","/article/",{"y":"p","t":"文章","I":false},[]],
  ["v-154dc4c4","/star/",{"y":"p","t":"收藏","I":false},[]],
  ["v-01560935","/timeline/",{"y":"p","t":"时间轴","I":false},[]],
  ["v-03d57386","/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/",{"y":"p","t":"使用指南 分类","I":false},["/category/使用指南/"]],
  ["v-83e1f92e","/tag/%E7%A6%81%E7%94%A8/",{"y":"p","t":"标签: 禁用","I":false},["/tag/禁用/"]],
  ["v-1e447d61","/tag/%E6%96%87%E7%AB%A0%E5%8A%A0%E5%AF%86/",{"y":"p","t":"标签: 文章加密","I":false},["/tag/文章加密/"]],
  ["v-484552dc","/tag/markdown/",{"y":"p","t":"标签: Markdown","I":false},[]],
  ["v-a378ad66","/tag/%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE/",{"y":"p","t":"标签: 页面配置","I":false},["/tag/页面配置/"]],
  ["v-7b167472","/tag/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/",{"y":"p","t":"标签: 使用指南","I":false},["/tag/使用指南/"]],
]
